default: &default
  adapter: postgresql
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: student_dashboard_development

production:
  <<: *default
  pool: 10
  database: student_dashboard_production
